spring:
  application:
    name: ApiGatewayApplication
  cloud:
    gateway:
      routes:
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
          filters:
            - name: CircuitBreaker
        - id: currency-conversion
          uri: lb:///currency-conversion
          predicates:
            - Path=/currency-conversion/**
          filters:
            - name: CircuitBreaker

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 5s
